void compare_emu_pid(const char* efile, const char* mufile, const char* outfile, const char* label1, const char* label2){


	std::cout <<"compare_emu_pid: Reading in files "<<efile<<" and "<<mufile<<std::endl;
	bool execute_program = true;

	ifstream file1(efile);
	if (!file1.good()) {
		std::cout <<"Specified electron file "<<efile<<" does not exist! Quit program..."<<std::endl;
		execute_program = false;
	}
	ifstream file2(mufile);
	if (!file2.good()){
		std::cout <<"Specified muon file "<<mufile<<" does not exist! Quit program..."<<std::endl;
		execute_program = false;
	}	


	if (execute_program){

		TFile *f_e = new TFile(efile,"READ");
		TFile *f_mu = new TFile(mufile,"READ");
		TFile *f_out = new TFile(outfile,"RECREATE");


		TH1F *hist_pmtPE_e = (TH1F*) f_e->Get("hist_pmtPE");
		TH1F *hist_pmtPE_mu = (TH1F*) f_mu->Get("hist_pmtPE");
		hist_pmtPE_e->Scale(1./hist_pmtPE_e->Integral());
		hist_pmtPE_mu->Scale(1./hist_pmtPE_mu->Integral());
		hist_pmtPE_mu->SetLineColor(2);
		TCanvas *c_pmtPE = new TCanvas("c_pmtPE","Canvas PMT P.E.",900,600);
		hist_pmtPE_e->Draw("hist");
		hist_pmtPE_mu->Draw("same hist");
		TLegend *leg = new TLegend(0.75,0.75,0.9,0.9);
		leg->AddEntry(hist_pmtPE_e,label1,"l");
		leg->AddEntry(hist_pmtPE_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtPE->Write();

		leg->Clear();
		TH1F *hist_pmtTime_e = (TH1F*) f_e->Get("hist_pmtTime");
		TH1F *hist_pmtTime_mu = (TH1F*) f_mu->Get("hist_pmtTime");
		hist_pmtTime_e->Scale(1./hist_pmtTime_e->Integral());
		hist_pmtTime_mu->Scale(1./hist_pmtTime_mu->Integral());
		hist_pmtTime_mu->SetLineColor(2);
		TCanvas *c_pmtTime = new TCanvas("c_pmtTime","Canvas PMT Time",900,600);
		hist_pmtTime_e->Draw("hist");
		leg->AddEntry(hist_pmtTime_e,label1,"l");
		leg->AddEntry(hist_pmtTime_mu,label2,"l");
		leg->Draw("same");
		hist_pmtTime_mu->Draw("same hist");
		f_out->cd();
		c_pmtTime->Write();

		leg->Clear();
		TH1F *hist_pmtAngle_e = (TH1F*) f_e->Get("hist_pmtAngle");
		TH1F *hist_pmtAngle_mu = (TH1F*) f_mu->Get("hist_pmtAngle");
		hist_pmtAngle_e->Scale(1./hist_pmtAngle_e->Integral());
		hist_pmtAngle_mu->Scale(1./hist_pmtAngle_mu->Integral());
		hist_pmtAngle_mu->SetLineColor(2);
		TCanvas *c_pmtAngle = new TCanvas("c_pmtAngle","Canvas PMT Angle",900,600);
		hist_pmtAngle_e->Draw("hist");
		hist_pmtAngle_mu->Draw("same hist");
		leg->AddEntry(hist_pmtAngle_e,label1,"l");
		leg->AddEntry(hist_pmtAngle_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtAngle->Write();

		leg->Clear();
		TH1F *hist_pmtDist_e = (TH1F*) f_e->Get("hist_pmtDist");
		TH1F *hist_pmtDist_mu = (TH1F*) f_mu->Get("hist_pmtDist");
		hist_pmtDist_e->Scale(1./hist_pmtDist_e->Integral());
		hist_pmtDist_mu->Scale(1./hist_pmtDist_mu->Integral());
		hist_pmtDist_mu->SetLineColor(2);
		TCanvas *c_pmtDist = new TCanvas("c_pmtDist","Canvas PMT Distance",900,600);
		hist_pmtDist_e->Draw("hist");
		hist_pmtDist_mu->Draw("same hist");
		leg->AddEntry(hist_pmtDist_e,label1,"l");
		leg->AddEntry(hist_pmtDist_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtDist->Write();

		leg->Clear();
		TH1F *hist_pmtHits_e = (TH1F*) f_e->Get("hist_pmtHits");
		TH1F *hist_pmtHits_mu = (TH1F*) f_mu->Get("hist_pmtHits");
		hist_pmtHits_e->Scale(1./hist_pmtHits_e->Integral());
		hist_pmtHits_mu->Scale(1./hist_pmtHits_mu->Integral());
		hist_pmtHits_mu->SetLineColor(2);
		TCanvas *c_pmtHits = new TCanvas("c_pmtHits","Canvas PMT Hits",900,600);
		hist_pmtHits_e->Draw("hist");
		hist_pmtHits_mu->Draw("same hist");
		leg->AddEntry(hist_pmtHits_e,label1,"l");
		leg->AddEntry(hist_pmtHits_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtHits->Write();

		leg->Clear();
		TH1F *hist_pmtPEtotal_e = (TH1F*) f_e->Get("hist_pmtPEtotal");
		TH1F *hist_pmtPEtotal_mu = (TH1F*) f_mu->Get("hist_pmtPEtotal");
		hist_pmtPEtotal_e->Scale(1./hist_pmtPEtotal_e->Integral());
		hist_pmtPEtotal_mu->Scale(1./hist_pmtPEtotal_mu->Integral());
		hist_pmtPEtotal_mu->SetLineColor(2);
		TCanvas *c_pmtPEtotal = new TCanvas("c_pmtPEtotal","Canvas PMT P.E. total",900,600);
		hist_pmtPEtotal_e->Draw("hist");
		hist_pmtPEtotal_mu->Draw("same hist");
		leg->AddEntry(hist_pmtPEtotal_e,label1,"l");
		leg->AddEntry(hist_pmtPEtotal_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtPEtotal->Write();

        	leg->Clear();
		TH1F *hist_pmtAvgTime_e = (TH1F*) f_e->Get("hist_pmtAvgTime");
		TH1F *hist_pmtAvgTime_mu = (TH1F*) f_mu->Get("hist_pmtAvgTime");
		hist_pmtAvgTime_e->Scale(1./hist_pmtAvgTime_e->Integral());
		hist_pmtAvgTime_mu->Scale(1./hist_pmtAvgTime_mu->Integral());
		hist_pmtAvgTime_mu->SetLineColor(2);
		TCanvas *c_pmtAvgTime = new TCanvas("c_pmtAvgTime","Canvas PMT Average Time",900,600);
		hist_pmtAvgTime_e->Draw("hist");
		hist_pmtAvgTime_mu->Draw("same hist");
		leg->AddEntry(hist_pmtAvgTime_e,label1,"l");
		leg->AddEntry(hist_pmtAvgTime_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtAvgTime->Write();

		leg->Clear();
        	TH1F *hist_pmtAngleBary_e = (TH1F*) f_e->Get("hist_pmtAngleBary");
		TH1F *hist_pmtAngleBary_mu = (TH1F*) f_mu->Get("hist_pmtAngleBary");
		hist_pmtAngleBary_e->Scale(1./hist_pmtAngleBary_e->Integral());
		hist_pmtAngleBary_mu->Scale(1./hist_pmtAngleBary_mu->Integral());
		hist_pmtAngleBary_mu->SetLineColor(2);
		TCanvas *c_pmtAngleBary = new TCanvas("c_pmtAngleBary","Canvas PMT Barycenter Angle",900,600);
		hist_pmtAngleBary_e->Draw("hist");
		hist_pmtAngleBary_mu->Draw("same hist");
		leg->AddEntry(hist_pmtAngleBary_e,label1,"l");
		leg->AddEntry(hist_pmtAngleBary_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtAngleBary->Write();

		leg->Clear();
		TH1F *hist_pmtAngleRMS_e = (TH1F*) f_e->Get("hist_pmtAngleRMS");
		TH1F *hist_pmtAngleRMS_mu = (TH1F*) f_mu->Get("hist_pmtAngleRMS");
		hist_pmtAngleRMS_e->Scale(1./hist_pmtAngleRMS_e->Integral());
		hist_pmtAngleRMS_mu->Scale(1./hist_pmtAngleRMS_mu->Integral());
		hist_pmtAngleRMS_mu->SetLineColor(2);
		TCanvas *c_pmtAngleRMS = new TCanvas("c_pmtAngleRMS","Canvas PMT Angular RMS",900,600);
		hist_pmtAngleRMS_e->Draw("hist");
		hist_pmtAngleRMS_mu->Draw("same hist");
		leg->AddEntry(hist_pmtAngleRMS_e,label1,"l");
		leg->AddEntry(hist_pmtAngleRMS_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtAngleRMS->Write();

		leg->Clear();
		TH1F *hist_pmtAngleVar_e = (TH1F*) f_e->Get("hist_pmtAngleVar");
		TH1F *hist_pmtAngleVar_mu = (TH1F*) f_mu->Get("hist_pmtAngleVar");
		hist_pmtAngleVar_e->Scale(1./hist_pmtAngleVar_e->Integral());
		hist_pmtAngleVar_mu->Scale(1./hist_pmtAngleVar_mu->Integral());
		hist_pmtAngleVar_mu->SetLineColor(2);
		TCanvas *c_pmtAngleVar = new TCanvas("c_pmtAngleVar","Canvas PMT Angular Variance",900,600);
		hist_pmtAngleVar_e->Draw("hist");
		hist_pmtAngleVar_mu->Draw("same hist");
		leg->AddEntry(hist_pmtAngleVar_e,label1,"l");
		leg->AddEntry(hist_pmtAngleVar_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtAngleVar->Write();

		leg->Clear();
        	TH1F *hist_pmtAngleSkew_e = (TH1F*) f_e->Get("hist_pmtAngleSkew");
		TH1F *hist_pmtAngleSkew_mu = (TH1F*) f_mu->Get("hist_pmtAngleSkew");
		hist_pmtAngleSkew_e->Scale(1./hist_pmtAngleSkew_e->Integral());
		hist_pmtAngleSkew_mu->Scale(1./hist_pmtAngleSkew_mu->Integral());
		hist_pmtAngleSkew_mu->SetLineColor(2);
		TCanvas *c_pmtAngleSkew = new TCanvas("c_pmtAngleSkew","Canvas PMT Angular Skewness",900,600);
		hist_pmtAngleSkew_e->Draw("hist");
		hist_pmtAngleSkew_mu->Draw("same hist");
		leg->AddEntry(hist_pmtAngleSkew_e,label1,"l");
		leg->AddEntry(hist_pmtAngleSkew_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtAngleSkew->Write();
                
		leg->Clear();
		TH1F *hist_pmtAngleKurt_e = (TH1F*) f_e->Get("hist_pmtAngleKurt");
		TH1F *hist_pmtAngleKurt_mu = (TH1F*) f_mu->Get("hist_pmtAngleKurt");
		hist_pmtAngleKurt_e->Scale(1./hist_pmtAngleKurt_e->Integral());
		hist_pmtAngleKurt_mu->Scale(1./hist_pmtAngleKurt_mu->Integral());
		hist_pmtAngleKurt_mu->SetLineColor(2);
		TCanvas *c_pmtAngleKurt = new TCanvas("c_pmtAngleKurt","Canvas PMT Angular Kurtosis",900,600);
		hist_pmtAngleKurt_e->Draw("hist");
		hist_pmtAngleKurt_mu->Draw("same hist");
		leg->AddEntry(hist_pmtAngleKurt_e,label1,"l");
		leg->AddEntry(hist_pmtAngleKurt_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtAngleKurt->Write();

		leg->Clear();
		TH1F *hist_pmtBaryRMS_e = (TH1F*) f_e->Get("hist_pmtBaryRMS");
		TH1F *hist_pmtBaryRMS_mu = (TH1F*) f_mu->Get("hist_pmtBaryRMS");
		hist_pmtBaryRMS_e->Scale(1./hist_pmtBaryRMS_e->Integral());
		hist_pmtBaryRMS_mu->Scale(1./hist_pmtBaryRMS_mu->Integral());
		hist_pmtBaryRMS_mu->SetLineColor(2);
		TCanvas *c_pmtBaryRMS = new TCanvas("c_pmtBaryRMS","Canvas PMT Barycenter Angular RMS",900,600);
		hist_pmtBaryRMS_e->Draw("hist");
		hist_pmtBaryRMS_mu->Draw("same hist");
		leg->AddEntry(hist_pmtBaryRMS_e,label1,"l");
		leg->AddEntry(hist_pmtBaryRMS_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtBaryRMS->Write();

		leg->Clear();
		TH1F *hist_pmtBaryVar_e = (TH1F*) f_e->Get("hist_pmtBaryVar");
		TH1F *hist_pmtBaryVar_mu = (TH1F*) f_mu->Get("hist_pmtBaryVar");
		hist_pmtBaryVar_e->Scale(1./hist_pmtBaryVar_e->Integral());
		hist_pmtBaryVar_mu->Scale(1./hist_pmtBaryVar_mu->Integral());
		hist_pmtBaryVar_mu->SetLineColor(2);
		TCanvas *c_pmtBaryVar = new TCanvas("c_pmtBaryVar","Canvas PMT Barycenter Angular Variance",900,600);
		hist_pmtBaryVar_e->Draw("hist");
		hist_pmtBaryVar_mu->Draw("same hist");
		leg->AddEntry(hist_pmtBaryVar_e,label1,"l");
		leg->AddEntry(hist_pmtBaryVar_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtBaryVar->Write();

		leg->Clear();
        	TH1F *hist_pmtBarySkew_e = (TH1F*) f_e->Get("hist_pmtBarySkew");
		TH1F *hist_pmtBarySkew_mu = (TH1F*) f_mu->Get("hist_pmtBarySkew");
		hist_pmtBarySkew_e->Scale(1./hist_pmtBarySkew_e->Integral());
		hist_pmtBarySkew_mu->Scale(1./hist_pmtBarySkew_mu->Integral());
		hist_pmtBarySkew_mu->SetLineColor(2);
		TCanvas *c_pmtBarySkew = new TCanvas("c_pmtBarySkew","Canvas PMT Barycenter Angular Skewness",900,600);
		hist_pmtBarySkew_e->Draw("hist");
		hist_pmtBarySkew_mu->Draw("same hist");
		leg->AddEntry(hist_pmtBarySkew_e,label1,"l");
		leg->AddEntry(hist_pmtBarySkew_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtBarySkew->Write();

		leg->Clear();
        	TH1F *hist_pmtBaryKurt_e = (TH1F*) f_e->Get("hist_pmtBaryKurt");
		TH1F *hist_pmtBaryKurt_mu = (TH1F*) f_mu->Get("hist_pmtBaryKurt");
		hist_pmtBaryKurt_e->Scale(1./hist_pmtBaryKurt_e->Integral());
		hist_pmtBaryKurt_mu->Scale(1./hist_pmtBaryKurt_mu->Integral());
		hist_pmtBaryKurt_mu->SetLineColor(2);
		TCanvas *c_pmtBaryKurt = new TCanvas("c_pmtBaryKurt","Canvas PMT Barycenter Angular Kurtosis",900,600);
		hist_pmtBaryKurt_e->Draw("hist");
		hist_pmtBaryKurt_mu->Draw("same hist");
		leg->AddEntry(hist_pmtBaryKurt_e,label1,"l");
		leg->AddEntry(hist_pmtBaryKurt_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtBaryKurt->Write();

		leg->Clear();
        	TH1F *hist_pmtFracRing_e = (TH1F*) f_e->Get("hist_pmtFracRing");
		TH1F *hist_pmtFracRing_mu = (TH1F*) f_mu->Get("hist_pmtFracRing");
		hist_pmtFracRing_e->Scale(1./hist_pmtFracRing_e->Integral());
		hist_pmtFracRing_mu->Scale(1./hist_pmtFracRing_mu->Integral());
		hist_pmtFracRing_mu->SetLineColor(2);
		TCanvas *c_pmtFracRing = new TCanvas("c_pmtFracRing","Canvas PMT Fraction Ring Hits weighted",900,600);
		hist_pmtFracRing_e->Draw("hist");
		hist_pmtFracRing_mu->Draw("same hist");
		leg->AddEntry(hist_pmtFracRing_e,label1,"l");
		leg->AddEntry(hist_pmtFracRing_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtFracRing->Write();

		leg->Clear();
        	TH1F *hist_pmtPhiBaryRMS_e = (TH1F*) f_e->Get("hist_pmtPhiBaryRMS");
		TH1F *hist_pmtPhiBaryRMS_mu = (TH1F*) f_mu->Get("hist_pmtPhiBaryRMS");
		hist_pmtPhiBaryRMS_e->Scale(1./hist_pmtPhiBaryRMS_e->Integral());
		hist_pmtPhiBaryRMS_mu->Scale(1./hist_pmtPhiBaryRMS_mu->Integral());
		hist_pmtPhiBaryRMS_mu->SetLineColor(2);
		TCanvas *c_pmtPhiBaryRMS = new TCanvas("c_pmtPhiBaryRMS","Canvas PMT Phi Barycenter RMS",900,600);
		hist_pmtPhiBaryRMS_e->Draw("hist");
		hist_pmtPhiBaryRMS_mu->Draw("same hist");
		leg->AddEntry(hist_pmtPhiBaryRMS_e,label1,"l");
		leg->AddEntry(hist_pmtPhiBaryRMS_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtPhiBaryRMS->Write();
		
		leg->Clear();
        	TH1F *hist_pmtPhiBaryVar_e = (TH1F*) f_e->Get("hist_pmtPhiBaryVar");
		TH1F *hist_pmtPhiBaryVar_mu = (TH1F*) f_mu->Get("hist_pmtPhiBaryVar");
		hist_pmtPhiBaryVar_e->Scale(1./hist_pmtPhiBaryVar_e->Integral());
		hist_pmtPhiBaryVar_mu->Scale(1./hist_pmtPhiBaryVar_mu->Integral());
		hist_pmtPhiBaryVar_mu->SetLineColor(2);
		TCanvas *c_pmtPhiBaryVar = new TCanvas("c_pmtPhiBaryVar","Canvas PMT Phi Barycenter Variance",900,600);
		hist_pmtPhiBaryVar_e->Draw("hist");
		hist_pmtPhiBaryVar_mu->Draw("same hist");
		leg->AddEntry(hist_pmtPhiBaryVar_e,label1,"l");
		leg->AddEntry(hist_pmtPhiBaryVar_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtPhiBaryVar->Write();
		
		leg->Clear();
        	TH1F *hist_pmtFracDownstream_e = (TH1F*) f_e->Get("hist_pmtFracDownstream");
		TH1F *hist_pmtFracDownstream_mu = (TH1F*) f_mu->Get("hist_pmtFracDownstream");
		hist_pmtFracDownstream_e->Scale(1./hist_pmtFracDownstream_e->Integral());
		hist_pmtFracDownstream_mu->Scale(1./hist_pmtFracDownstream_mu->Integral());
		hist_pmtFracDownstream_mu->SetLineColor(2);
		TCanvas *c_pmtFracDownstream = new TCanvas("c_pmtFracDownstream","Canvas PMT Fraction Downstream Q",900,600);
		hist_pmtFracDownstream_e->Draw("hist");
		hist_pmtFracDownstream_mu->Draw("same hist");
		leg->AddEntry(hist_pmtFracDownstream_e,label1,"l");
		leg->AddEntry(hist_pmtFracDownstream_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtFracDownstream->Write();

		leg->Clear();
		TH1F *hist_pmtFracRingNoWeight_e = (TH1F*) f_e->Get("hist_pmtFracRingNoWeight");
		TH1F *hist_pmtFracRingNoWeight_mu = (TH1F*) f_mu->Get("hist_pmtFracRingNoWeight");
		hist_pmtFracRingNoWeight_e->Scale(1./hist_pmtFracRingNoWeight_e->Integral());
		hist_pmtFracRingNoWeight_mu->Scale(1./hist_pmtFracRingNoWeight_mu->Integral());
		hist_pmtFracRingNoWeight_mu->SetLineColor(2);
		TCanvas *c_pmtFracRingNoWeight = new TCanvas("c_pmtFracRingNoWeight","Canvas PMT Fraction Ring Hits",900,600);
		hist_pmtFracRingNoWeight_e->Draw("hist");
		hist_pmtFracRingNoWeight_mu->Draw("same hist");
		leg->AddEntry(hist_pmtFracRingNoWeight_e,label1,"l");
		leg->AddEntry(hist_pmtFracRingNoWeight_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtFracRingNoWeight->Write();

		leg->Clear();
		TH1F *hist_pmtFracHighestQ_e = (TH1F*) f_e->Get("hist_pmtFracHighestQ");
        	TH1F *hist_pmtFracHighestQ_mu = (TH1F*) f_mu->Get("hist_pmtFracHighestQ");
        	hist_pmtFracHighestQ_e->Scale(1./hist_pmtFracHighestQ_e->Integral());
		hist_pmtFracHighestQ_mu->Scale(1./hist_pmtFracHighestQ_mu->Integral());
		hist_pmtFracHighestQ_mu->SetLineColor(2);
		TCanvas *c_pmtFracHighestQ = new TCanvas("c_pmtFracHighestQ","Canvas PMT Fraction Highest Q",900,600);
		hist_pmtFracHighestQ_e->Draw("hist");
		hist_pmtFracHighestQ_mu->Draw("same hist");
		leg->AddEntry(hist_pmtFracHighestQ_e,label1,"l");
		leg->AddEntry(hist_pmtFracHighestQ_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtFracHighestQ->Write();

		leg->Clear();
		TH1F *hist_pmtFracLowCharge_e = (TH1F*) f_e->Get("hist_pmtFracLowCharge");
        	TH1F *hist_pmtFracLowCharge_mu = (TH1F*) f_mu->Get("hist_pmtFracLowCharge");
        	hist_pmtFracLowCharge_e->Scale(1./hist_pmtFracLowCharge_e->Integral());
		hist_pmtFracLowCharge_mu->Scale(1./hist_pmtFracLowCharge_mu->Integral());
		hist_pmtFracLowCharge_mu->SetLineColor(2);
		TCanvas *c_pmtFracLowCharge = new TCanvas("c_pmtFracLowCharge","Canvas PMT Fraction Low Charge Hits",900,600);
		hist_pmtFracLowCharge_e->Draw("hist");
		hist_pmtFracLowCharge_mu->Draw("same hist");
		leg->AddEntry(hist_pmtFracLowCharge_e,label1,"l");
		leg->AddEntry(hist_pmtFracLowCharge_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtFracLowCharge->Write();
		
		leg->Clear();
		TH1F *hist_pmtFracLateTime_e = (TH1F*) f_e->Get("hist_pmtFracLateTime");
        	TH1F *hist_pmtFracLateTime_mu = (TH1F*) f_mu->Get("hist_pmtFracLateTime");
        	hist_pmtFracLateTime_e->Scale(1./hist_pmtFracLateTime_e->Integral());
		hist_pmtFracLateTime_mu->Scale(1./hist_pmtFracLateTime_mu->Integral());
		hist_pmtFracLateTime_mu->SetLineColor(2);
		TCanvas *c_pmtFracLateTime = new TCanvas("c_pmtFracLateTime","Canvas PMT Fraction Late Time Hits",900,600);
		hist_pmtFracLateTime_e->Draw("hist");
		hist_pmtFracLateTime_mu->Draw("same hist");
		leg->AddEntry(hist_pmtFracLateTime_e,label1,"l");
		leg->AddEntry(hist_pmtFracLateTime_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtFracLateTime->Write();
		
		leg->Clear();
		TH1F *hist_pmtAngleBary_all_e = (TH1F*) f_e->Get("hist_pmtAngleBary_all");
        	TH1F *hist_pmtAngleBary_all_mu = (TH1F*) f_mu->Get("hist_pmtAngleBary_all");
        	hist_pmtAngleBary_all_e->Scale(1./hist_pmtAngleBary_all_e->Integral());
		hist_pmtAngleBary_all_mu->Scale(1./hist_pmtAngleBary_all_mu->Integral());
		hist_pmtAngleBary_all_mu->SetLineColor(2);
		TCanvas *c_pmtAngleBary_all = new TCanvas("c_pmtAngleBary_all","Canvas PMT Barycenter",900,600);
		hist_pmtAngleBary_all_e->Draw("hist");
		hist_pmtAngleBary_all_mu->Draw("same hist");
		leg->AddEntry(hist_pmtAngleBary_all_e,label1,"l");
		leg->AddEntry(hist_pmtAngleBary_all_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtAngleBary_all->Write();
		
		leg->Clear();
		TH1F *hist_pmtAngleBary_all_ChargeWeighted_e = (TH1F*) f_e->Get("hist_pmtAngleBary_all_ChargeWeighted");
        	TH1F *hist_pmtAngleBary_all_ChargeWeighted_mu = (TH1F*) f_mu->Get("hist_pmtAngleBary_all_ChargeWeighted");
        	hist_pmtAngleBary_all_ChargeWeighted_e->Scale(1./hist_pmtAngleBary_all_ChargeWeighted_e->Integral());
		hist_pmtAngleBary_all_ChargeWeighted_mu->Scale(1./hist_pmtAngleBary_all_ChargeWeighted_mu->Integral());
		hist_pmtAngleBary_all_ChargeWeighted_mu->SetLineColor(2);
		TCanvas *c_pmtAngleBary_all_ChargeWeighted = new TCanvas("c_pmtAngleBary_all_ChargeWeighted","Canvas PMT Barycenter weighted",900,600);
		hist_pmtAngleBary_all_ChargeWeighted_e->Draw("hist");
		hist_pmtAngleBary_all_ChargeWeighted_mu->Draw("same hist");
		leg->AddEntry(hist_pmtAngleBary_all_ChargeWeighted_e,label1,"l");
		leg->AddEntry(hist_pmtAngleBary_all_ChargeWeighted_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtAngleBary_all_ChargeWeighted->Write();
		
		leg->Clear();
		TH1F *hist_pmtAngle2Bary_all_e = (TH1F*) f_e->Get("hist_pmtAngle2Bary_all");
        	TH1F *hist_pmtAngle2Bary_all_mu = (TH1F*) f_mu->Get("hist_pmtAngle2Bary_all");
        	hist_pmtAngle2Bary_all_e->Scale(1./hist_pmtAngle2Bary_all_e->Integral());
		hist_pmtAngle2Bary_all_mu->Scale(1./hist_pmtAngle2Bary_all_mu->Integral());
		hist_pmtAngle2Bary_all_mu->SetLineColor(2);
		TCanvas *c_pmtAngle2Bary_all = new TCanvas("c_pmtAngle2Bary_all","Canvas PMT Angle2 Barycenter",900,600);
		hist_pmtAngle2Bary_all_e->Draw("hist");
		hist_pmtAngle2Bary_all_mu->Draw("same hist");
		leg->AddEntry(hist_pmtAngle2Bary_all_e,label1,"l");
		leg->AddEntry(hist_pmtAngle2Bary_all_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtAngle2Bary_all->Write();
		
		leg->Clear();
		TH1F *hist_pmtAngle2Bary_all_ChargeWeighted_e = (TH1F*) f_e->Get("hist_pmtAngle2Bary_all_ChargeWeighted");
        	TH1F *hist_pmtAngle2Bary_all_ChargeWeighted_mu = (TH1F*) f_mu->Get("hist_pmtAngle2Bary_all_ChargeWeighted");
        	hist_pmtAngle2Bary_all_ChargeWeighted_e->Scale(1./hist_pmtAngle2Bary_all_ChargeWeighted_e->Integral());
		hist_pmtAngle2Bary_all_ChargeWeighted_mu->Scale(1./hist_pmtAngle2Bary_all_ChargeWeighted_mu->Integral());
		hist_pmtAngle2Bary_all_ChargeWeighted_mu->SetLineColor(2);
		TCanvas *c_pmtAngle2Bary_all_ChargeWeighted = new TCanvas("c_pmtAngle2Bary_all_ChargeWeighted","Canvas PMT Angle2 Barycenter weighted",900,600);
		hist_pmtAngle2Bary_all_ChargeWeighted_e->Draw("hist");
		hist_pmtAngle2Bary_all_ChargeWeighted_mu->Draw("same hist");
		leg->AddEntry(hist_pmtAngle2Bary_all_ChargeWeighted_e,label1,"l");
		leg->AddEntry(hist_pmtAngle2Bary_all_ChargeWeighted_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtAngle2Bary_all_ChargeWeighted->Write();
		
		leg->Clear();
		TH1F *hist_pmtYBary_all_e = (TH1F*) f_e->Get("hist_pmtYBary_all");
        	TH1F *hist_pmtYBary_all_mu = (TH1F*) f_mu->Get("hist_pmtYBary_all");
        	hist_pmtYBary_all_e->Scale(1./hist_pmtYBary_all_e->Integral());
		hist_pmtYBary_all_mu->Scale(1./hist_pmtYBary_all_mu->Integral());
		hist_pmtYBary_all_mu->SetLineColor(2);
		TCanvas *c_pmtYBary_all = new TCanvas("c_pmtYBary_all","Canvas PMT Y Barycenter",900,600);
		hist_pmtYBary_all_e->Draw("hist");
		hist_pmtYBary_all_mu->Draw("same hist");
		leg->AddEntry(hist_pmtYBary_all_e,label1,"l");
		leg->AddEntry(hist_pmtYBary_all_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtYBary_all->Write();
		
		leg->Clear();
		TH1F *hist_pmtYBary_all_ChargeWeighted_e = (TH1F*) f_e->Get("hist_pmtYBary_all_ChargeWeighted");
        	TH1F *hist_pmtYBary_all_ChargeWeighted_mu = (TH1F*) f_mu->Get("hist_pmtYBary_all_ChargeWeighted");
        	hist_pmtYBary_all_ChargeWeighted_e->Scale(1./hist_pmtYBary_all_ChargeWeighted_e->Integral());
		hist_pmtYBary_all_ChargeWeighted_mu->Scale(1./hist_pmtYBary_all_ChargeWeighted_mu->Integral());
		hist_pmtYBary_all_ChargeWeighted_mu->SetLineColor(2);
		TCanvas *c_pmtYBary_all_ChargeWeighted = new TCanvas("c_pmtYBary_all_ChargeWeighted","Canvas PMT Y Barycenter weighted",900,600);
		hist_pmtYBary_all_ChargeWeighted_e->Draw("hist");
		hist_pmtYBary_all_ChargeWeighted_mu->Draw("same hist");
		leg->AddEntry(hist_pmtYBary_all_ChargeWeighted_e,label1,"l");
		leg->AddEntry(hist_pmtYBary_all_ChargeWeighted_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtYBary_all_ChargeWeighted->Write();
		
		leg->Clear();
		TH1F *hist_pmtPhiBary_all_e = (TH1F*) f_e->Get("hist_pmtPhiBary_all");
        	TH1F *hist_pmtPhiBary_all_mu = (TH1F*) f_mu->Get("hist_pmtPhiBary_all");
        	hist_pmtPhiBary_all_e->Scale(1./hist_pmtPhiBary_all_e->Integral());
		hist_pmtPhiBary_all_mu->Scale(1./hist_pmtPhiBary_all_mu->Integral());
		hist_pmtPhiBary_all_mu->SetLineColor(2);
		TCanvas *c_pmtPhiBary_all = new TCanvas("c_pmtPhiBary_all","Canvas PMT Phi Barycenter",900,600);
		hist_pmtPhiBary_all_e->Draw("hist");
		hist_pmtPhiBary_all_mu->Draw("same hist");
		leg->AddEntry(hist_pmtPhiBary_all_e,label1,"l");
		leg->AddEntry(hist_pmtPhiBary_all_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtPhiBary_all->Write();
		
		leg->Clear();
		TH1F *hist_pmtPhiBary_all_ChargeWeighted_e = (TH1F*) f_e->Get("hist_pmtPhiBary_all_ChargeWeighted");
        	TH1F *hist_pmtPhiBary_all_ChargeWeighted_mu = (TH1F*) f_mu->Get("hist_pmtPhiBary_all_ChargeWeighted");
        	hist_pmtPhiBary_all_ChargeWeighted_e->Scale(1./hist_pmtPhiBary_all_ChargeWeighted_e->Integral());
		hist_pmtPhiBary_all_ChargeWeighted_mu->Scale(1./hist_pmtPhiBary_all_ChargeWeighted_mu->Integral());
		hist_pmtPhiBary_all_ChargeWeighted_mu->SetLineColor(2);
		TCanvas *c_pmtPhiBary_all_ChargeWeighted = new TCanvas("c_pmtPhiBary_all_ChargeWeighted","Canvas PMT Phi Barycenter weighted",900,600);
		hist_pmtPhiBary_all_ChargeWeighted_e->Draw("hist");
		hist_pmtPhiBary_all_ChargeWeighted_mu->Draw("same hist");
		leg->AddEntry(hist_pmtPhiBary_all_ChargeWeighted_e,label1,"l");
		leg->AddEntry(hist_pmtPhiBary_all_ChargeWeighted_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtPhiBary_all_ChargeWeighted->Write();
		
		leg->Clear();
		TH1F *hist_pmtPhiBaryFracLargeAngle_e = (TH1F*) f_e->Get("hist_pmtPhiBaryFracLargeAngle");
        	TH1F *hist_pmtPhiBaryFracLargeAngle_mu = (TH1F*) f_mu->Get("hist_pmtPhiBaryFracLargeAngle");
        	hist_pmtPhiBaryFracLargeAngle_e->Scale(1./hist_pmtPhiBaryFracLargeAngle_e->Integral());
		hist_pmtPhiBaryFracLargeAngle_mu->Scale(1./hist_pmtPhiBaryFracLargeAngle_mu->Integral());
		hist_pmtPhiBaryFracLargeAngle_mu->SetLineColor(2);
		TCanvas *c_pmtPhiBaryFracLargeAngle = new TCanvas("c_pmtPhiBaryFracLargeAngle","Canvas PMT Fraction Large Angle Phi",900,600);
		hist_pmtPhiBaryFracLargeAngle_e->Draw("hist");
		hist_pmtPhiBaryFracLargeAngle_mu->Draw("same hist");
		leg->AddEntry(hist_pmtPhiBaryFracLargeAngle_e,label1,"l");
		leg->AddEntry(hist_pmtPhiBaryFracLargeAngle_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtPhiBaryFracLargeAngle->Write();
		
		leg->Clear();
		TH1F *hist_pmtFracEarlyTime_e = (TH1F*) f_e->Get("hist_pmtFracEarlyTime");
        	TH1F *hist_pmtFracEarlyTime_mu = (TH1F*) f_mu->Get("hist_pmtFracEarlyTime");
        	hist_pmtFracEarlyTime_e->Scale(1./hist_pmtFracEarlyTime_e->Integral());
		hist_pmtFracEarlyTime_mu->Scale(1./hist_pmtFracEarlyTime_mu->Integral());
		hist_pmtFracEarlyTime_mu->SetLineColor(2);
		TCanvas *c_pmtFracEarlyTime = new TCanvas("c_pmtFracEarlyTime","Canvas PMT Fraction Early Hits",900,600);
		hist_pmtFracEarlyTime_e->Draw("hist");
		hist_pmtFracEarlyTime_mu->Draw("same hist");
		leg->AddEntry(hist_pmtFracEarlyTime_e,label1,"l");
		leg->AddEntry(hist_pmtFracEarlyTime_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtFracEarlyTime->Write();
		
		leg->Clear();
		TH1F *hist_pmtBaryFracLargeAngle_e = (TH1F*) f_e->Get("hist_pmtBaryFracLargeAngle");
        	TH1F *hist_pmtBaryFracLargeAngle_mu = (TH1F*) f_mu->Get("hist_pmtBaryFracLargeAngle");
        	hist_pmtBaryFracLargeAngle_e->Scale(1./hist_pmtBaryFracLargeAngle_e->Integral());
		hist_pmtBaryFracLargeAngle_mu->Scale(1./hist_pmtBaryFracLargeAngle_mu->Integral());
		hist_pmtBaryFracLargeAngle_mu->SetLineColor(2);
		TCanvas *c_pmtBaryFracLargeAngle = new TCanvas("c_pmtBaryFracLargeAngle","Canvas PMT Fraction Large Angle Hits",900,600);
		hist_pmtBaryFracLargeAngle_e->Draw("hist");
		hist_pmtBaryFracLargeAngle_mu->Draw("same hist");
		leg->AddEntry(hist_pmtBaryFracLargeAngle_e,label1,"l");
		leg->AddEntry(hist_pmtBaryFracLargeAngle_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_pmtBaryFracLargeAngle->Write();
		
		leg->Clear();
		TH1F *hist_lappdPE_e = (TH1F*) f_e->Get("hist_lappdPE");
		TH1F *hist_lappdPE_mu = (TH1F*) f_mu->Get("hist_lappdPE");
		hist_lappdPE_e->Scale(1./hist_lappdPE_e->Integral());
		hist_lappdPE_mu->Scale(1./hist_lappdPE_mu->Integral());
		hist_lappdPE_mu->SetLineColor(2);
		TCanvas *c_lappdPE = new TCanvas("c_lappdPE","Canvas lappd P.E.",900,600);
		hist_lappdPE_e->Draw("hist");
		hist_lappdPE_mu->Draw("same hist");
		leg->AddEntry(hist_lappdPE_e,label1,"l");
		leg->AddEntry(hist_lappdPE_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_lappdPE->Write();

		leg->Clear();
		TH1F *hist_lappdTime_e = (TH1F*) f_e->Get("hist_lappdTime");
		TH1F *hist_lappdTime_mu = (TH1F*) f_mu->Get("hist_lappdTime");
		hist_lappdTime_e->Scale(1./hist_lappdTime_e->Integral());
		hist_lappdTime_mu->Scale(1./hist_lappdTime_mu->Integral());
		hist_lappdTime_mu->SetLineColor(2);
		TCanvas *c_lappdTime = new TCanvas("c_lappdTime","Canvas lappd Time",900,600);
		hist_lappdTime_e->Draw("hist");
		hist_lappdTime_mu->Draw("same hist");
		leg->AddEntry(hist_lappdPE_e,label1,"l");
		leg->AddEntry(hist_lappdPE_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_lappdTime->Write();

		leg->Clear();
		TH1F *hist_lappdAngle_e = (TH1F*) f_e->Get("hist_lappdAngle");
		TH1F *hist_lappdAngle_mu = (TH1F*) f_mu->Get("hist_lappdAngle");
		hist_lappdAngle_e->Scale(1./hist_lappdAngle_e->Integral());
		hist_lappdAngle_mu->Scale(1./hist_lappdAngle_mu->Integral());
		hist_lappdAngle_mu->SetLineColor(2);
		TCanvas *c_lappdAngle = new TCanvas("c_lappdAngle","Canvas lappd Angle",900,600);
		hist_lappdAngle_e->Draw("hist");
		hist_lappdAngle_mu->Draw("same hist");
		leg->AddEntry(hist_lappdAngle_e,label1,"l");
		leg->AddEntry(hist_lappdAngle_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_lappdAngle->Write();

		leg->Clear();
		TH1F *hist_lappdDist_e = (TH1F*) f_e->Get("hist_lappdDist");
		TH1F *hist_lappdDist_mu = (TH1F*) f_mu->Get("hist_lappdDist");
		hist_lappdDist_e->Scale(1./hist_lappdDist_e->Integral());
		hist_lappdDist_mu->Scale(1./hist_lappdDist_mu->Integral());
		hist_lappdDist_mu->SetLineColor(2);
		TCanvas *c_lappdDist = new TCanvas("c_lappdDist","Canvas lappd Distance",900,600);
		hist_lappdDist_e->Draw("hist");
		hist_lappdDist_mu->Draw("same hist");
		leg->AddEntry(hist_lappdDist_e,label1,"l");
		leg->AddEntry(hist_lappdDist_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_lappdDist->Write();

		leg->Clear();
		TH1F *hist_lappdHits_e = (TH1F*) f_e->Get("hist_lappdHits");
		TH1F *hist_lappdHits_mu = (TH1F*) f_mu->Get("hist_lappdHits");
		hist_lappdHits_e->Scale(1./hist_lappdHits_e->Integral());
		hist_lappdHits_mu->Scale(1./hist_lappdHits_mu->Integral());
		hist_lappdHits_mu->SetLineColor(2);
		TCanvas *c_lappdHits = new TCanvas("c_lappdHits","Canvas lappd Hits",900,600);
		hist_lappdHits_e->Draw("hist");
		hist_lappdHits_mu->Draw("same hist");
		leg->AddEntry(hist_lappdHits_e,label1,"l");
		leg->AddEntry(hist_lappdHits_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_lappdHits->Write();

		leg->Clear();
		TH1F *hist_lappdPEtotal_e = (TH1F*) f_e->Get("hist_lappdPEtotal");
		TH1F *hist_lappdPEtotal_mu = (TH1F*) f_mu->Get("hist_lappdPEtotal");
		hist_lappdPEtotal_e->Scale(1./hist_lappdPEtotal_e->Integral());
		hist_lappdPEtotal_mu->Scale(1./hist_lappdPEtotal_mu->Integral());
		hist_lappdPEtotal_mu->SetLineColor(2);
		TCanvas *c_lappdPEtotal = new TCanvas("c_lappdPEtotal","Canvas lappd P.E. total",900,600);
		hist_lappdPEtotal_e->Draw("hist");
		hist_lappdPEtotal_mu->Draw("same hist");
		leg->AddEntry(hist_lappdPEtotal_e,label1,"l");
		leg->AddEntry(hist_lappdPEtotal_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_lappdPEtotal->Write();

		leg->Clear();
       		TH1F *hist_lappdAvgTime_e = (TH1F*) f_e->Get("hist_lappdAvgTime");
		TH1F *hist_lappdAvgTime_mu = (TH1F*) f_mu->Get("hist_lappdAvgTime");
		hist_lappdAvgTime_e->Scale(1./hist_lappdAvgTime_e->Integral());
		hist_lappdAvgTime_mu->Scale(1./hist_lappdAvgTime_mu->Integral());
		hist_lappdAvgTime_mu->SetLineColor(2);
		TCanvas *c_lappdAvgTime = new TCanvas("c_lappdAvgTime","Canvas lappd Average Time",900,600);
		hist_lappdAvgTime_e->Draw("hist");
		hist_lappdAvgTime_mu->Draw("same hist");
		leg->AddEntry(hist_lappdAvgTime_e,label1,"l");
		leg->AddEntry(hist_lappdAvgTime_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_lappdAvgTime->Write();

		leg->Clear();
        	TH1F *hist_lappdAngleBary_e = (TH1F*) f_e->Get("hist_lappdAngleBary");
		TH1F *hist_lappdAngleBary_mu = (TH1F*) f_mu->Get("hist_lappdAngleBary");
		hist_lappdAngleBary_e->Scale(1./hist_lappdAngleBary_e->Integral());
		hist_lappdAngleBary_mu->Scale(1./hist_lappdAngleBary_mu->Integral());
		hist_lappdAngleBary_mu->SetLineColor(2);
		TCanvas *c_lappdAngleBary = new TCanvas("c_lappdAngleBary","Canvas lappd Barycenter Angle",900,600);
		hist_lappdAngleBary_e->Draw("hist");
		hist_lappdAngleBary_mu->Draw("same hist");
		leg->AddEntry(hist_lappdAngleBary_e,label1,"l");
		leg->AddEntry(hist_lappdAngleBary_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_lappdAngleBary->Write();

		leg->Clear();
		TH1F *hist_lappdAngleRMS_e = (TH1F*) f_e->Get("hist_lappdAngleRMS");
		TH1F *hist_lappdAngleRMS_mu = (TH1F*) f_mu->Get("hist_lappdAngleRMS");
		hist_lappdAngleRMS_e->Scale(1./hist_lappdAngleRMS_e->Integral());
		hist_lappdAngleRMS_mu->Scale(1./hist_lappdAngleRMS_mu->Integral());
		hist_lappdAngleRMS_mu->SetLineColor(2);
		TCanvas *c_lappdAngleRMS = new TCanvas("c_lappdAngleRMS","Canvas lappd Angular RMS",900,600);
		hist_lappdAngleRMS_e->Draw("hist");
		hist_lappdAngleRMS_mu->Draw("same hist");
		leg->AddEntry(hist_lappdAngleRMS_e,label1,"l");
		leg->AddEntry(hist_lappdAngleRMS_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_lappdAngleRMS->Write();

		leg->Clear();
		TH1F *hist_lappdAngleVar_e = (TH1F*) f_e->Get("hist_lappdAngleVar");
		TH1F *hist_lappdAngleVar_mu = (TH1F*) f_mu->Get("hist_lappdAngleVar");
		hist_lappdAngleVar_e->Scale(1./hist_lappdAngleVar_e->Integral());
		hist_lappdAngleVar_mu->Scale(1./hist_lappdAngleVar_mu->Integral());
		hist_lappdAngleVar_mu->SetLineColor(2);
		TCanvas *c_lappdAngleVar = new TCanvas("c_lappdAngleVar","Canvas lappd Angular Variance",900,600);
		hist_lappdAngleVar_e->Draw("hist");
		hist_lappdAngleVar_mu->Draw("same hist");
		leg->AddEntry(hist_lappdAngleVar_e,label1,"l");
		leg->AddEntry(hist_lappdAngleVar_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_lappdAngleVar->Write();

		leg->Clear();
        	TH1F *hist_lappdAngleSkew_e = (TH1F*) f_e->Get("hist_lappdAngleSkew");
		TH1F *hist_lappdAngleSkew_mu = (TH1F*) f_mu->Get("hist_lappdAngleSkew");
		hist_lappdAngleSkew_e->Scale(1./hist_lappdAngleSkew_e->Integral());
		hist_lappdAngleSkew_mu->Scale(1./hist_lappdAngleSkew_mu->Integral());
		hist_lappdAngleSkew_mu->SetLineColor(2);
		TCanvas *c_lappdAngleSkew = new TCanvas("c_lappdAngleSkew","Canvas lappd Angular Skewness",900,600);
		hist_lappdAngleSkew_e->Draw("hist");
		hist_lappdAngleSkew_mu->Draw("same hist");
		leg->AddEntry(hist_lappdAngleSkew_e,label1,"l");
		leg->AddEntry(hist_lappdAngleSkew_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_lappdAngleSkew->Write();
                
		leg->Clear();
		TH1F *hist_lappdAngleKurt_e = (TH1F*) f_e->Get("hist_lappdAngleKurt");
		TH1F *hist_lappdAngleKurt_mu = (TH1F*) f_mu->Get("hist_lappdAngleKurt");
		hist_lappdAngleKurt_e->Scale(1./hist_lappdAngleKurt_e->Integral());
		hist_lappdAngleKurt_mu->Scale(1./hist_lappdAngleKurt_mu->Integral());
		hist_lappdAngleKurt_mu->SetLineColor(2);
		TCanvas *c_lappdAngleKurt = new TCanvas("c_lappdAngleKurt","Canvas lappd Angular Kurtosis",900,600);
		hist_lappdAngleKurt_e->Draw("hist");
		hist_lappdAngleKurt_mu->Draw("same hist");
		leg->AddEntry(hist_lappdAngleKurt_e,label1,"l");
		leg->AddEntry(hist_lappdAngleKurt_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_lappdAngleKurt->Write();

		leg->Clear();
		TH1F *hist_lappdBaryRMS_e = (TH1F*) f_e->Get("hist_lappdBaryRMS");
		TH1F *hist_lappdBaryRMS_mu = (TH1F*) f_mu->Get("hist_lappdBaryRMS");
		hist_lappdBaryRMS_e->Scale(1./hist_lappdBaryRMS_e->Integral());
		hist_lappdBaryRMS_mu->Scale(1./hist_lappdBaryRMS_mu->Integral());
		hist_lappdBaryRMS_mu->SetLineColor(2);
		TCanvas *c_lappdBaryRMS = new TCanvas("c_lappdBaryRMS","Canvas lappd Barycenter Angular RMS",900,600);
		hist_lappdBaryRMS_e->Draw("hist");
		hist_lappdBaryRMS_mu->Draw("same hist");
		leg->AddEntry(hist_lappdBaryRMS_e,label1,"l");
		leg->AddEntry(hist_lappdBaryRMS_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_lappdBaryRMS->Write();

		leg->Clear();
		TH1F *hist_lappdBaryVar_e = (TH1F*) f_e->Get("hist_lappdBaryVar");
		TH1F *hist_lappdBaryVar_mu = (TH1F*) f_mu->Get("hist_lappdBaryVar");
		hist_lappdBaryVar_e->Scale(1./hist_lappdBaryVar_e->Integral());
		hist_lappdBaryVar_mu->Scale(1./hist_lappdBaryVar_mu->Integral());
		hist_lappdBaryVar_mu->SetLineColor(2);
		TCanvas *c_lappdBaryVar = new TCanvas("c_lappdBaryVar","Canvas lappd Barycenter Angular Variance",900,600);
		hist_lappdBaryVar_e->Draw("hist");
		hist_lappdBaryVar_mu->Draw("same hist");
		leg->AddEntry(hist_lappdBaryVar_e,label1,"l");
		leg->AddEntry(hist_lappdBaryVar_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_lappdBaryVar->Write();

		leg->Clear();
        	TH1F *hist_lappdBarySkew_e = (TH1F*) f_e->Get("hist_lappdBarySkew");
		TH1F *hist_lappdBarySkew_mu = (TH1F*) f_mu->Get("hist_lappdBarySkew");
		hist_lappdBarySkew_e->Scale(1./hist_lappdBarySkew_e->Integral());
		hist_lappdBarySkew_mu->Scale(1./hist_lappdBarySkew_mu->Integral());
		hist_lappdBarySkew_mu->SetLineColor(2);
		TCanvas *c_lappdBarySkew = new TCanvas("c_lappdBarySkew","Canvas lappd Barycenter Angular Skewness",900,600);
		hist_lappdBarySkew_e->Draw("hist");
		hist_lappdBarySkew_mu->Draw("same hist");
		leg->AddEntry(hist_lappdBarySkew_e,label1,"l");
		leg->AddEntry(hist_lappdBarySkew_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_lappdBarySkew->Write();

		leg->Clear();
        	TH1F *hist_lappdBaryKurt_e = (TH1F*) f_e->Get("hist_lappdBaryKurt");
		TH1F *hist_lappdBaryKurt_mu = (TH1F*) f_mu->Get("hist_lappdBaryKurt");
		hist_lappdBaryKurt_e->Scale(1./hist_lappdBaryKurt_e->Integral());
		hist_lappdBaryKurt_mu->Scale(1./hist_lappdBaryKurt_mu->Integral());
		hist_lappdBaryKurt_mu->SetLineColor(2);
		TCanvas *c_lappdBaryKurt = new TCanvas("c_lappdBaryKurt","Canvas lappd Barycenter Angular Kurtosis",900,600);
		hist_lappdBaryKurt_e->Draw("hist");
		hist_lappdBaryKurt_mu->Draw("same hist");
		leg->AddEntry(hist_lappdBaryKurt_e,label1,"l");
		leg->AddEntry(hist_lappdBaryKurt_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_lappdBaryKurt->Write();

		leg->Clear();
        	TH1F *hist_lappdFracRing_e = (TH1F*) f_e->Get("hist_lappdFracRing");
		TH1F *hist_lappdFracRing_mu = (TH1F*) f_mu->Get("hist_lappdFracRing");
		hist_lappdFracRing_e->Scale(1./hist_lappdFracRing_e->Integral());
		hist_lappdFracRing_mu->Scale(1./hist_lappdFracRing_mu->Integral());
		hist_lappdFracRing_mu->SetLineColor(2);
		TCanvas *c_lappdFracRing = new TCanvas("c_lappdFracRing","Canvas lappd Fraction Ring Hits weighted",900,600);
		hist_lappdFracRing_e->Draw("hist");
		hist_lappdFracRing_mu->Draw("same hist");
		leg->AddEntry(hist_lappdFracRing_e,label1,"l");
		leg->AddEntry(hist_lappdFracRing_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_lappdFracRing->Write();

		leg->Clear();
		TH1F *hist_lappdFracRingNoWeight_e = (TH1F*) f_e->Get("hist_lappdFracRingNoWeight");
		TH1F *hist_lappdFracRingNoWeight_mu = (TH1F*) f_mu->Get("hist_lappdFracRingNoWeight");
		hist_lappdFracRingNoWeight_e->Scale(1./hist_lappdFracRingNoWeight_e->Integral());
		hist_lappdFracRingNoWeight_mu->Scale(1./hist_lappdFracRingNoWeight_mu->Integral());
		hist_lappdFracRingNoWeight_mu->SetLineColor(2);
		TCanvas *c_lappdFracRingNoWeight = new TCanvas("c_lappdFracRingNoWeight","Canvas lappd Fraction Ring Hits",900,600);
		hist_lappdFracRingNoWeight_e->Draw("hist");
		hist_lappdFracRingNoWeight_mu->Draw("same hist");
		leg->AddEntry(hist_lappdFracRingNoWeight_e,label1,"l");
		leg->AddEntry(hist_lappdFracRingNoWeight_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_lappdFracRingNoWeight->Write();


		leg->Clear();
        	TH1F *hist_mrdPaddles_e = (TH1F*) f_e->Get("hist_mrdPaddles");
		TH1F *hist_mrdPaddles_mu = (TH1F*) f_mu->Get("hist_mrdPaddles");
		hist_mrdPaddles_e->Scale(1./hist_mrdPaddles_e->Integral());
		hist_mrdPaddles_mu->Scale(1./hist_mrdPaddles_mu->Integral());
		hist_mrdPaddles_mu->SetLineColor(2);
		TCanvas *c_mrdPaddles = new TCanvas("c_mrdPaddles","Canvas MRD Paddles",900,600);
		hist_mrdPaddles_e->Draw("hist");
		hist_mrdPaddles_mu->Draw("same hist");
		leg->AddEntry(hist_mrdPaddles_e,label1,"l");
		leg->AddEntry(hist_mrdPaddles_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_mrdPaddles->Write();

                leg->Clear();
		TH1F *hist_mrdLayers_e = (TH1F*) f_e->Get("hist_mrdLayers");
        	TH1F *hist_mrdLayers_mu = (TH1F*) f_mu->Get("hist_mrdLayers");
       		hist_mrdLayers_e->Scale(1./hist_mrdLayers_e->Integral());
		hist_mrdLayers_mu->Scale(1./hist_mrdLayers_mu->Integral());
		hist_mrdLayers_mu->SetLineColor(2);
		TCanvas *c_mrdLayers = new TCanvas("c_mrdLayers","Canvas MRD Layers",900,600);
		hist_mrdLayers_e->Draw("hist");
		hist_mrdLayers_mu->Draw("same hist");
		leg->AddEntry(hist_mrdLayers_e,label1,"l");
		leg->AddEntry(hist_mrdLayers_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_mrdLayers->Write();

		leg->Clear();
		TH1F *hist_mrdconsLayers_e = (TH1F*) f_e->Get("hist_mrdconsLayers");
		TH1F *hist_mrdconsLayers_mu = (TH1F*) f_mu->Get("hist_mrdconsLayers");
		hist_mrdconsLayers_e->Scale(1./hist_mrdconsLayers_e->Integral());
		hist_mrdconsLayers_mu->Scale(1./hist_mrdconsLayers_mu->Integral());
		hist_mrdconsLayers_mu->SetLineColor(2);
		TCanvas *c_mrdconsLayers = new TCanvas("c_mrdconsLayers","Canvas MRD consecutive Layers",900,600);
		hist_mrdconsLayers_e->Draw("hist");
		hist_mrdconsLayers_mu->Draw("same hist");
		leg->AddEntry(hist_mrdconsLayers_e,label1,"l");
		leg->AddEntry(hist_mrdconsLayers_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_mrdconsLayers->Write();
		
		leg->Clear();
		TH1F *hist_mrdXSpread_e = (TH1F*) f_e->Get("hist_mrdXSpread");
		TH1F *hist_mrdXSpread_mu = (TH1F*) f_mu->Get("hist_mrdXSpread");
		hist_mrdXSpread_e->Scale(1./hist_mrdXSpread_e->Integral());
		hist_mrdXSpread_mu->Scale(1./hist_mrdXSpread_mu->Integral());
		hist_mrdXSpread_mu->SetLineColor(2);
		TCanvas *c_mrdXSpread = new TCanvas("c_mrdXSpread","Canvas MRD X Spread",900,600);
		hist_mrdXSpread_e->Draw("hist");
		hist_mrdXSpread_mu->Draw("same hist");
		leg->AddEntry(hist_mrdXSpread_e,label1,"l");
		leg->AddEntry(hist_mrdXSpread_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_mrdXSpread->Write();

		leg->Clear();
		TH1F *hist_mrdYSpread_e = (TH1F*) f_e->Get("hist_mrdYSpread");
		TH1F *hist_mrdYSpread_mu = (TH1F*) f_mu->Get("hist_mrdYSpread");
		hist_mrdYSpread_e->Scale(1./hist_mrdYSpread_e->Integral());
		hist_mrdYSpread_mu->Scale(1./hist_mrdYSpread_mu->Integral());
		hist_mrdYSpread_mu->SetLineColor(2);
		TCanvas *c_mrdYSpread = new TCanvas("c_mrdYSpread","Canvas MRD Y Spread",900,600);
		hist_mrdYSpread_e->Draw("hist");
		hist_mrdYSpread_mu->Draw("same hist");
		leg->AddEntry(hist_mrdYSpread_e,label1,"l");
		leg->AddEntry(hist_mrdYSpread_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_mrdYSpread->Write();

		leg->Clear();
		TH1F *hist_mrdPaddlesPerLayer_e = (TH1F*) f_e->Get("hist_mrdPaddlesPerLayer");
		TH1F *hist_mrdPaddlesPerLayer_mu = (TH1F*) f_mu->Get("hist_mrdPaddlesPerLayer");
		hist_mrdPaddlesPerLayer_e->Scale(1./hist_mrdPaddlesPerLayer_e->Integral());
		hist_mrdPaddlesPerLayer_mu->Scale(1./hist_mrdPaddlesPerLayer_mu->Integral());
		hist_mrdPaddlesPerLayer_mu->SetLineColor(2);
		TCanvas *c_mrdPaddlesPerLayer = new TCanvas("c_mrdPaddlesPerLayer","Canvas MRD Paddles Per Layer",900,600);
		hist_mrdPaddlesPerLayer_e->Draw("hist");
		hist_mrdPaddlesPerLayer_mu->Draw("same hist");
		leg->AddEntry(hist_mrdPaddlesPerLayer_e,label1,"l");
		leg->AddEntry(hist_mrdPaddlesPerLayer_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_mrdPaddlesPerLayer->Write();
		
		leg->Clear();
		TH1F *hist_mrdAdjacentHits_e = (TH1F*) f_e->Get("hist_mrdAdjacentHits");
		TH1F *hist_mrdAdjacentHits_mu = (TH1F*) f_mu->Get("hist_mrdAdjacentHits");
		hist_mrdAdjacentHits_e->Scale(1./hist_mrdAdjacentHits_e->Integral());
		hist_mrdAdjacentHits_mu->Scale(1./hist_mrdAdjacentHits_mu->Integral());
		hist_mrdAdjacentHits_mu->SetLineColor(2);
		TCanvas *c_mrdAdjacentHits = new TCanvas("c_mrdAdjacentHits","Canvas MRD Adjacent Hits",900,600);
		hist_mrdAdjacentHits_e->Draw("hist");
		hist_mrdAdjacentHits_mu->Draw("same hist");
		leg->AddEntry(hist_mrdAdjacentHits_e,label1,"l");
		leg->AddEntry(hist_mrdAdjacentHits_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_mrdAdjacentHits->Write();

		leg->Clear();
		TH1F *hist_mrdClusters_e = (TH1F*) f_e->Get("hist_mrdClusters");
		TH1F *hist_mrdClusters_mu = (TH1F*) f_mu->Get("hist_mrdClusters");
		hist_mrdClusters_e->Scale(1./hist_mrdconsLayers_e->Integral());
		hist_mrdClusters_mu->Scale(1./hist_mrdconsLayers_mu->Integral());
		hist_mrdClusters_mu->SetLineColor(2);
		TCanvas *c_mrdClusters = new TCanvas("c_mrdClusters","Canvas MRD Clusters",900,600);
		hist_mrdClusters_e->Draw("hist");
		hist_mrdClusters_mu->Draw("same hist");
		leg->AddEntry(hist_mrdClusters_e,label1,"l");
		leg->AddEntry(hist_mrdClusters_mu,label2,"l");
		leg->Draw("same");
		f_out->cd();
		c_mrdClusters->Write();

                leg->Clear();
                TH1F *hist_energy_e = (TH1F*) f_e->Get("hist_energy");
                TH1F *hist_energy_mu = (TH1F*) f_mu->Get("hist_energy");
                hist_energy_e->Scale(1./hist_energy_e->Integral());
                hist_energy_mu->Scale(1./hist_energy_mu->Integral());
                hist_energy_mu->SetLineColor(2);
                TCanvas *c_energy = new TCanvas("c_energy","Canvas Energies",900,600);
                hist_energy_e->Draw("hist");
                hist_energy_mu->Draw("same hist");
                leg->AddEntry(hist_energy_e,label1,"l");
                leg->AddEntry(hist_energy_mu,label2,"l");
                leg->Draw("same");
                f_out->cd();
                c_energy->Write();

                leg->Clear();
                TH1F *hist_nrings_e = (TH1F*) f_e->Get("hist_nrings");
                TH1F *hist_nrings_mu = (TH1F*) f_mu->Get("hist_nrings");
                hist_nrings_e->Scale(1./hist_nrings_e->Integral());
                hist_nrings_mu->Scale(1./hist_nrings_mu->Integral());
                hist_nrings_mu->SetLineColor(2);
                TCanvas *c_nrings = new TCanvas("c_nrings","Canvas N Rings",900,600);
                hist_nrings_e->Draw("hist");
                hist_nrings_mu->Draw("same hist");
                leg->AddEntry(hist_nrings_e,label1,"l");
                leg->AddEntry(hist_nrings_mu,label2,"l");
                leg->Draw("same");
                f_out->cd();
                c_nrings->Write();

                leg->Clear();
                TH1F *hist_multiple_rings_e = (TH1F*) f_e->Get("hist_multiple_rings");
                TH1F *hist_multiple_rings_mu = (TH1F*) f_mu->Get("hist_multiple_rings");
                hist_multiple_rings_e->Scale(1./hist_multiple_rings_e->Integral());
                hist_multiple_rings_mu->Scale(1./hist_multiple_rings_mu->Integral());
                hist_multiple_rings_mu->SetLineColor(2);
                TCanvas *c_multiple_rings = new TCanvas("c_multiple_rings","Canvas Multiple Rings",900,600);
                hist_multiple_rings_e->Draw("hist");
                hist_multiple_rings_mu->Draw("same hist");
                leg->AddEntry(hist_multiple_rings_e,label1,"l");
                leg->AddEntry(hist_multiple_rings_mu,label2,"l");
                leg->Draw("same");
                f_out->cd();
                c_multiple_rings->Write();


		f_out->Close();
		f_e->Close();
		f_mu->Close();

		delete f_out;
		delete f_e;
		delete f_mu;


	}




}
